sila/homepage/urls.py
from django.urls import path
from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.homepage, name="home"),
    path("upload/", views.upload, name="upload"),
    path("process_coordinates/", views.process_coordinates, name="process_coordinates"),
    path("modelfit/", views.learn, name="learn"),
]

sila/sila/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

sila/homepage/models.py
from django.db import models

# Create your models here.

sila/homepage/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), label='Выберите изображения')

sila/homepage/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
import pandas as pd
import json
from PIL import Image
import uuid
import os

d = {'царапины': 0, 'битые пиксели': 1, 'проблемы с клавишами': 2, 'замок': 3, 
     'отсутствует шуруп': 4, 'сколы': 5, 'специфический': 6}


def delete_image(filename):
    filepath = os.path.join(settings.BASE_DIR, "images", filename)
    if os.path.exists(filepath):
        os.remove(filepath)
        print("deleted")
    else:
        print("error")


def homepage(request):
    template = "homepage/home.html"
    df = pd.read_csv(os.path.join(settings.BASE_DIR, "src", "data.csv"))
    num_rows = len(df)
    context = {"num_rows": num_rows}
    return render(request, template_name=template, context=context)


def upload(request):
    if request.method == 'POST' and request.FILES.getlist('images'):
        images = request.FILES.getlist('images')
        image_names = []
        predicted_images = []
        for image in images:
            unique_filename = str(uuid.uuid4()) + os.path.splitext(image.name)[-1]
            fs = FileSystemStorage()
            fs.save("images/" + unique_filename, image)
            fs.save("learn_images/" + unique_filename, image)
            image_names.append(unique_filename)
        results = settings.MODEL.predict(os.path.join(settings.BASE_DIR, "images"))
        for i in image_names:
            delete_image(i)
        for i, r in enumerate(results):
            name = image_names[i]
            print(name)
            r.save(filename=os.path.join("src", "predicted_images", name))
            predicted_images.append(name)
        return render(request, 'homepage/upload_success.html', {"images": predicted_images})
    return render(request, 'homepage/upload_fail.html')


def process_coordinates(request):
  if request.method == 'POST':
    data = json.loads(request.body)
    image = data.get('image')
    point1 = data.get('point1')
    point2 = data.get('point2')
    damageclass = data.get('damage_class')
    filename = data.get('image')
    filename = filename.split("/")[-1]
    x1, y1, x2, y2 = int(point1['x']), int(point1['y']), int(point2['x']), int(point2['y'])
    dx, dy = int(min(x1, x2)), int(max(y1, y2))
    width = int(abs(max(x1, x2) - dx))
    length = int(abs(dy - min(y2, y1)))
    df = pd.DataFrame(columns=['main_class','filename','x_left_bottom','y_left_bottom','length','width'])
    df.loc[len(df)] = [d[damageclass.lower()],filename,dx,dy,length,width]
    old_df = pd.read_csv(os.path.join(settings.BASE_DIR, "src", "data.csv"))
    combined = pd.concat([old_df, df], ignore_index=True).drop_duplicates()
    combined.to_csv(os.path.join(settings.BASE_DIR, "src", "data.csv"), index=False)
    

    return render(request, 'base.html', {'images': []}) # Возвращаем шаблон (или другой ответ)
  else:
    return render(request, 'base.html', {'images': []}) # Возвращаем шаблон (или другой ответ)



# MODEL_FITTING

def learn(request):
    import cv2
    import os
    import numpy as np
    import pandas as pd
    from django.conf import settings

    df = pd.read_csv(os.path.join(settings.BASE_DIR, "src", "data.csv"), delimiter=",")
    if len(df) < 10:
        return render(request, 'homepage/home.html', {'error_message': 'Должно быть не менее 10 записей в базе данных', 'num_rows': len(df)})

    input_folder = os.path.join(settings.BASE_DIR, 'learn_images')
    output_folder = os.path.join(settings.BASE_DIR, 'src', 'dataset', 'train')
    output_images_folder = os.path.join(output_folder, 'images')
    output_labels_folder = os.path.join(output_folder, 'labels')

    resize_const = 640

    os.makedirs(output_images_folder, exist_ok=True)
    os.makedirs(output_labels_folder, exist_ok=True)

    def normalize_coordinates(x1, y1, x2, y2, img_width, img_height):
        x_center = (x1 + x2) / 2 / img_width
        y_center = (y1 + y2) / 2 / img_height
        width = abs(x2 - x1) / img_width
        height = abs(y2 - y1) / img_height
        return x_center, y_center, width, height

    for filename in os.listdir(input_folder):
        image_path = input_folder + "/" + filename
        image = cv2.imread(image_path)
        if len(df[df['filename']==filename].values) != 0:
            resized_image = cv2.resize(image, (resize_const, resize_const))
            x1, y1, length, w = (df[df['filename']==filename].values[0][2:6])
            
            x2 = x1 + length
            y2 = y1 - w
            # # Вырезаем область изображения
            # cropped_image = image[y2:y1, x1:x2]
            # print(len(cropped_image))

            # # Сохраняем или отображаем вырезанное изображение
            # cv2.imshow('Cropped Image', cropped_image)
            # cv2.waitKey(0)  # Ожидаем нажатия клавиши
            x_center, y_center, width, height = normalize_coordinates(x1, y1, x2, y2, image.shape[1], image.shape[0])

            # Сохранение изображения
            output_image_path = os.path.join(output_images_folder, filename)
            cv2.imwrite(output_image_path, resized_image)
            
            # Сохранение 
            label_filename = os.path.splitext(filename)[0] + '.txt'
            label_file_path = os.path.join(output_labels_folder, label_filename)
            with open(label_file_path, 'w') as f:
                f.write(f"{df[df['filename']==filename].values[0][0]} {x_center} {y_center} {width} {height}\n")
            print(f"Processed and saved {filename}")

    # SECOND PART

    import os
    import shutil
    import random

    # Параметры для разделения данных
    test_percent = 0.2  # Процент данных для тестирования
    valid_percent = 0.1  # Процент данных для проверки

    # Путь к папке с данными
    dataset_path = os.path.join(settings.BASE_DIR, 'src', 'dataset')
    train_images_path = os.path.join(dataset_path, 'train', 'images')
    train_labels_path = os.path.join(dataset_path, 'train', 'labels')
    valid_images_path = os.path.join(dataset_path, 'valid', 'images')
    valid_labels_path = os.path.join(dataset_path, 'valid', 'labels')
    test_images_path = os.path.join(dataset_path, 'test', 'images')
    test_labels_path = os.path.join(dataset_path, 'test', 'labels')

    os.makedirs(valid_images_path, exist_ok=True)
    os.makedirs(valid_labels_path, exist_ok=True)
    os.makedirs(test_images_path, exist_ok=True)
    os.makedirs(test_labels_path, exist_ok=True)

    # Получение всех файлов изображений и соответствующих меток
    images = [f for f in os.listdir(train_images_path)]
    labels = [f for f in os.listdir(train_labels_path)]
    print(len(images))

    # Убедимся, что количество изображений и меток совпадает
    images.sort()
    labels.sort()

    # Проверка на соответствие количества изображений и меток
    if len(images) != len(labels):
        print("Количество изображений и меток не совпадает.")
        exit()

    # Перемешивание данных
    data = list(zip(images, labels))
    random.shuffle(data)
    images, labels = zip(*data)
    print(images)
    print(labels)

    # Разделение данных
    num_images = len(images)
    num_test = int(num_images * test_percent)
    num_valid = int(num_images * valid_percent)
    num_train = num_images - num_test - num_valid

    # Перемещение данных в соответствующие папки
    def move_files(file_list, source_image_dir, source_label_dir, dest_image_dir, dest_label_dir):
        for file in file_list:
            image_path = os.path.join(source_image_dir, file)
            label_path = os.path.join(source_label_dir, os.path.splitext(file)[0] + '.txt')
            shutil.move(image_path, os.path.join(dest_image_dir, file))
            shutil.move(label_path, os.path.join(dest_label_dir, os.path.splitext(file)[0] + '.txt'))

    # Перемещение тестовых данных
    move_files(images[:num_test], train_images_path, train_labels_path, test_images_path, test_labels_path)

    # Перемещение валидационных данных
    move_files(images[num_test:num_test + num_valid], train_images_path, train_labels_path, valid_images_path, valid_labels_path)

    # Оставшиеся данные остаются в папке train

    print(f"Перемещено {num_test} изображений в папку test.")
    print(f"Перемещено {num_valid} изображений в папку valid.")
    print(f"Осталось {num_train} изображений в папке train.")

    data_path = os.path.join(settings.BASE_DIR, "src", "data.yaml")
    epoch_num = settings.EPOCH_NUM
    settings.MODEL.train(data=data_path, epochs=epoch_num)
    settings.MODEL.save(os.path.join(settings.BASE_DIR, "model", "best.pt"))

    for filename in os.listdir(input_folder):
        file_path = os.path.join(input_folder, filename)
        if os.path.isfile(file_path):
            os.remove(file_path)

    dff = pd.DataFrame(columns=['main_class', 'filename', 'x_left_bottom', 'y_left_bottom', 'length', 'width'])
    dff.to_csv(os.path.join(settings.BASE_DIR, "src", "data.csv"), index=False)
    return redirect('homepage:home')

sila/templates/homepage/home.html
{% extends "base.html" %}
{% block title %} Главная {% endblock %}
{% block content%}

<div class="container mt-5">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1 class="mb-4">Анализ дефектов ноутбуков</h1>
        <p class="lead mb-5">Загрузите изображения ноутбуков, и наша нейронная сеть определит класс дефекта (скол, царапина и т.д.).</p>
      </div>
    </div>
    
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card shadow-sm border-0 rounded">
          <div class="card-body p-4">
            <form action="/upload/" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              <div class="form-group">
                <label for="imageUpload" class="form-label">Загрузите изображения:</label>
                <input type="file" class="form-control-file" id="imageUpload" name="images" accept="image/*" multiple required>
              </div>
              <div id="imagePreview" class="mt-3"></div>
              <button type="submit" class="btn btn-primary mt-3">Отправить на анализ</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row justify-content-center mt-4">
    <div class="col-md-8">
      <p>В данный момент в базе данных: <strong>{{ num_rows }}</strong> записей.</p>
      <button class="btn btn-success" onclick="location.href='{% url 'homepage:learn' %}';">Дообучить модель</button>
    </div>
  </div>
  {% if error_message %}
  <div class="row justify-content-center mt-4">
      <div class="col-md-8">
          <div class="alert alert-danger" role="alert">
              {{ error_message }}
          </div>
      </div>
  </div>
  {% endif %}
</div>

<script>
  const imageUpload = document.getElementById('imageUpload');
  const imagePreview = document.getElementById('imagePreview');

  imageUpload.addEventListener('change', (event) => {
    const files = event.target.files;
    imagePreview.innerHTML = '';

    for (const file of files) {
      if (file.type.startsWith('image/')) {
        const reader = new FileReader();

        reader.onload = (e) => {
          const img = document.createElement('img');
          img.src = e.target.result;
          img.classList.add('img-fluid', 'mb-2');
          img.style.maxWidth = '150px';
          img.style.maxHeight = '100px';

          imagePreview.appendChild(img);
        }

        reader.readAsDataURL(file);
      }
    }
  });
</script>

{% endblock %}

sila/templates/homepage/upload_fail.html
{% extends "base.html" %}
{% block title %} Неудачная загрузка {% endblock %}
{% block content%}
<div class="row mt-5">
  <div class="col">
    <h1>Обработка изображения не удалась :(</h1>
    <p>Пожалуйста, попробуйте еще раз.</p>
  </div>
</div>
{% endblock %}

sila/templates/homepage/upload_success.html
{% extends "base.html" %}
{% block title %} Обработка {% endblock %}
{% block content%}
{% load static %}
{% csrf_token %}

<div class="row mt-5">
  <div class="col-md-12 text-center">
    <h1>Успех!</h1>
  </div>
</div>

<div class="row mt-5">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <div id="image-gallery">
          {% for image in images %}
            <img src="{% static 'predicted_images/' %}{{ image }}" 
                 data-image-path="{% static 'predicted_images/' %}{{ image }}" 
                 class="gallery-image" alt="{{ image }}">
          {% endfor %}
        </div>
      </div>
      <div class="col-md-8" id="image-container">
        <canvas id="image-canvas"></canvas>
      </div>
    </div>
    <div class="row mt-3">
      <div class="col-md-6">
        <label for="damage-class">Класс повреждения:</label>
        <select id="damage-class">
          <option value="царапины">Царапины</option>
          <option value="битые пиксели">Битые пиксели</option>
          <option value="проблемы с клавишами">Проблемы с клавишами</option>
          <option value="замок">Замок</option>
          <option value="отсутствует шуруп">Отсутствует шуруп</option>
          <option value="сколы">Сколы</option>
          <option value="специфический">Специфический</option>
        </select>
      </div>
      <div class="col-md-6 text-center">
        <button id="submit-coordinates" class="btn btn-primary btn-lg">Отправить на дообучение</button>
      </div>
    </div>
  </div>
</div>


<script>
  var csrftoken = '{{ csrf_token }}';
  const imageGallery = document.getElementById('image-gallery');
  const imageContainer = document.getElementById('image-container');
  const imageCanvas = document.getElementById('image-canvas');
  const ctx = imageCanvas.getContext('2d');
  const submitButton = document.getElementById('submit-coordinates');
  const damageClassSelect = document.getElementById('damage-class');
  
  let selectedImage = null;
  let selectedImageWidth = 0;
  let selectedImageHeight = 0;
  let point1 = null;
  let point2 = null;
  
  // Обработка клика по изображению в галерее
  imageGallery.addEventListener('click', (event) => {
   if (event.target.tagName === 'IMG') {
    const previousImage = document.querySelector('.gallery-image.selected');
    if (previousImage) {
     previousImage.classList.remove('selected');
    }
  
    event.target.classList.add('selected');
  
    selectedImage = new Image();
    selectedImage.src = event.target.dataset.imagePath;
  
    selectedImage.onload = () => {
     ctx.clearRect(0, 0, imageCanvas.width, imageCanvas.height);
  
     // Ограничение размера изображения на canvas
     const maxWidth = imageContainer.offsetWidth; // Получаем ширину контейнера
     const maxHeight = 500; // Установите максимальную высоту
  
     let newWidth = selectedImage.width;
     let newHeight = selectedImage.height;
     if (newWidth > maxWidth || newHeight > maxHeight) {
      if (newWidth / maxWidth > newHeight / maxHeight) {
       newHeight = maxWidth * (newHeight / newWidth);
       newWidth = maxWidth;
      } else {
       newWidth = maxHeight * (newWidth / newHeight);
       newHeight = maxHeight;
      }
     }
  
     imageCanvas.width = newWidth;
     imageCanvas.height = newHeight;
  
     // Выравнивание изображения по центру
     ctx.drawImage(
      selectedImage,
      (imageCanvas.width - newWidth) / 2, // Вычисляем смещение по горизонтали
      (imageCanvas.height - newHeight) / 2, // Вычисляем смещение по вертикали
      newWidth,
      newHeight
     );
  
     selectedImageWidth = newWidth;
     selectedImageHeight = newHeight;
    }
   }
  });
  
  // Обработка клика на canvas для рисования точек
  imageCanvas.addEventListener('click', (event) => {
   const rect = imageCanvas.getBoundingClientRect();
   const x = event.clientX - rect.left;
   const y = event.clientY - rect.top;
  
   const imageX = x / (imageCanvas.width / selectedImageWidth);
   const imageY = y / (imageCanvas.height / selectedImageHeight);
  
   ctx.save();
   if (point1 === null) {
    point1 = { x: imageX, y: imageY };
    ctx.beginPath();
    ctx.arc(x, y, 5, 0, 2 * Math.PI);
    ctx.fillStyle = 'red';
    ctx.fill();
   } else if (point2 === null) {
    point2 = { x: imageX, y: imageY };
    ctx.beginPath();
    ctx.arc(x, y, 5, 0, 2 * Math.PI);
    ctx.fillStyle = 'blue';
    ctx.fill();
  
    const minX = Math.min(point1.x, point2.x);
    const minY = Math.min(point1.y, point2.y);
    const width = Math.abs(point1.x - point2.x);
    const height = Math.abs(point1.y - point2.y);
    ctx.strokeStyle = 'green';
    ctx.strokeRect(
     minX * (imageCanvas.width / selectedImageWidth),
     minY * (imageCanvas.height / selectedImageHeight),
     width * (imageCanvas.width / selectedImageWidth),
     height * (imageCanvas.height / selectedImageHeight)
    );
   } else {
    ctx.clearRect(0, 0, imageCanvas.width, imageCanvas.height);
    imageCanvas.width = imageCanvas.width;
    imageCanvas.height = imageCanvas.height;
    point1 = null;
    point2 = null;
    point1 = { x: imageX, y: imageY };
    ctx.drawImage(selectedImage, 0, 0, imageCanvas.width, imageCanvas.height);
    selectedImageWidth = selectedImage.width;
    selectedImageHeight = selectedImage.height;
    ctx.beginPath();
    ctx.arc(x, y, 5, 0, 2 * Math.PI);
    ctx.fillStyle = 'red';
    ctx.fill();
   }
  
   ctx.restore();
  });
  
  // Обработка клика на кнопку "Отправить координаты"
  submitButton.addEventListener('click', () => {
   if (point1 && point2) {
    const currentImage = selectedImage.src;
    const damageClass = damageClassSelect.value;
  
    fetch('/process_coordinates/', {
     method: 'POST',
     headers: {
      'Content-Type': 'application/json',
      'X-CSRFToken': csrftoken,
     },
     body: JSON.stringify({
      image: currentImage,
      point1: point1,
      point2: point2,
      damage_class: damageClass,
     }),
    })
    .then(response => {
     if (response.ok) {
      return response.json();
     } else {
      throw new Error('Ошибка при отправке координат.');
     }
    })
    .then(data => {
     console.log('Ответ от сервера:', data);
    })
    .catch(error => {
     console.error('Ошибка:', error);
    });
   } else {
    alert('Пожалуйста, поставьте две точки на изображении.');
   }
  });
    
</script>

{% endblock %}